name: Python Semantic Release

on:
  push:
    branches:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@v9.21.0
