name: Python Semantic Release

permissions:
  id-token: write
  contents: write

on:
  push:
    branches:
      - 'main'

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout Repository
        uses: actions/checkout@v4

      - name: Setup | Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Setup | Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry==2.1.1
          poetry install --only dev,test

      - name: Action | Run pre-commit
        run: pre-commit run --all-files

      - name: Action | Run Tests
        run: pytest tests/

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout Repository on Release Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Setup | Force release branch to be at workflow sha
        run: |
          git reset --hard ${{ github.sha }}

      - name: Action | Semantic Version Release
        id: release
        uses: python-semantic-release/python-semantic-release@v9.21.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_name: "github-actions"
          git_committer_email: "actions@users.noreply.github.com"
